spring:
  application:
    name: postService
server:
  port: 8081
logbook:
  format:
    style: http
management:
  endpoints:
    web:
      exposure:
        include: mappings
liquibase:
  outputFile: src/main/resources/db/db.changelog-master.xml