spring:
  application:
    name: postService
server:
  port: 8081
logbook:
  format:
    style: http
management:
  endpoints:
    web:
      exposure:
        include: mappings
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml