spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/commentDb
    driverClassName: org.postgresql.Driver
    password: admin12345
  liquibase:
    changeLog: db/changelog/db.changelog-master.xml
keycloak:
  enabled: true
  auth-server-url: http://localhost:8080
  credentials:
    secret: BZNtImdA8OerDoIvwztjsJOJ6WIFzISu
  ssl-required: external
  realm: techbee
  resource: comment_service_client
  bearer-only: true
  use-resource-role-mappings: false