spring:
  application:
    name: commentService
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/commentDb
    driverClassName: org.postgresql.Driver
    password: admin12345
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8082
  servlet:
    context-path: /commentService
keycloak:
  enabled: true
  auth-server-url: http://localhost:8080
  credentials:
    secret: BZNtImdA8OerDoIvwztjsJOJ6WIFzISu
  ssl-required: external
  realm: techbee
  resource: comment_service_client
  bearer-only: true
  use-resource-role-mappings: false
logbook:
  format:
    style: http
management:
  endpoint:
    health:
      show-details: always
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
logging:
  level:
    org:
      keycloak: DEBUG