spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/commentDb}
    driverClassName: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD:admin12345}
  liquibase:
    changeLog: db/changelog/db.changelog-master.xml
keycloak:
  enabled: true
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:S8cQ9J4fnQ4E89YUR9WVanJGPwXJwCDc}
  ssl-required: external
  realm: ${KEYCLOAK_REALM:techbee}
  resource: comment_service_client
  bearer-only: true
  use-resource-role-mappings: false