spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://commentsdb.cpeem5xmvx4h.ap-south-1.rds.amazonaws.com:5432/postgres
    driverClassName: org.postgresql.Driver
    password: admin12345
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
keycloak:
  enabled: true
  auth-server-url: http://auth-server:8080
  credentials:
    secret: hUeVtun1XSJaRYm95i0tIxXFyVtCJPxI
  ssl-required: external
  realm: techbee
  resource: comment_service_client
  bearer-only: true
  use-resource-role-mappings: false