spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/techbeeDb
    driverClassName: org.postgresql.Driver
    password: admin12345
  jpa:
    hibernate:
      ddl-auto: update
liquibase:
  changeLogFile: src/main/resources/db/db.changelog-master.xml