apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: comment-service
  name: comment-service
  namespace: default
spec:
  ports:
    - # nodePort: 30702 #CHANGE
      port: 8082 #CHANGE
      protocol: TCP
      targetPort: 8082 #CHANGE
  selector:
    app: comment-service
  sessionAffinity: None #CHANGE
  type: LoadBalancer